apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gnvu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gnvu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gnvu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gnvu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gnvu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-flig-tenant/rhtap-demo-app/hacbs-test-project-gnvu@sha256:514ec19a9a7546db9e55e2f15c1e4580f36f6f1f1bfc19e44dd5ddbcef1a065b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
